# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Keach Your Kids
description: >- # this means to ignore newlines until "baseurl:"
  Adaptations of catechisms in modern English for children.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keach.jdbvs.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jonathanvanschenck

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - raw/
  - scripts/
  - node_modules/
  - data/
  - temp/
  - package.json
  - package-lock.json
  - README.md


defaults:
  -
    scope:
      path: "questions"
    values:
      layout: "question"
  -
    scope:
      path: "questions/keach"
    values:
      catechism: "keach"
      subtitle: "Keach's Catechism"
      short_description: "An adaptation of Keach's Catechism in modern English."
  -
    scope:
      path: "printable/keach.md"
    values:
      layout: "question"
      catechism: "keach"
      subtitle: "Keach's Catechism"
      short_description: "An adaptation of Keach's Catechism in modern English."
  -
    scope:
      path: "tocs/keach.md"
    values:
      catechism: "keach"
      subtitle: "Keach's Catechism"
      short_description: "An adaptation of Keach's Catechism in modern English."
  -
    scope:
      path: "questions/cfyc"
    values:
      catechism: "cfyc"
      subtitle: "Catechism for Young Children"
      short_description: "An adaptation of the Catechism for Young Children in modern English."
  -
    scope:
      path: "printable/cfyc.md"
    values:
      layout: "question"
      catechism: "cfyc"
      subtitle: "Catechism for Young Children"
      short_description: "An adaptation of the Catechism for Young Children in modern English."
  -
    scope:
      path: "tocs/cfyc.md"
    values:
      catechism: "cfyc"
      subtitle: "Catechism for Young Children"
      short_description: "An adaptation of the Catechism for Young Children in modern English."
